### ISSUE TITLE
CompQ_Loader

### ISSUE THREAD

**Issue by w5688414** [uhh-lt/BlurbGenreCollection-HMC#1]
I run your model, but I enounter an error, can you provide this source code:
`  File "main.py", line 7, in <module>
    from data_helpers import load_data, extract_hierarchies, remove_genres_not_level
  File "/home/eric/Documents/Experiments/BlurbGenreCollection_Classification/code/data_helpers.py", line 11, in <module>
    from comp_questions_loader import CompQ_Loader
ModuleNotFoundError: No module named 'comp_questions_loader'`

**Comment by Raldir** [comment]
Thank you for this information and excuse me for the late reply! This was an outdated dependency and has subsequently been removed.
